version: '3.4'
services:
  apache:
    build:
      context: ./
      dockerfile: ./infrastructure/containers/apache/Dockerfile
      target: production
    container_name: apache
    networks:
      - app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: ./infrastructure/containers/php/Dockerfile
      target: production
    container_name: php
    environment:
      - maildev_host=maildev
      - APP_ENV=prod
    networks:
      - app
    depends_on:
      - maildev
      - mysql

  lg_redis:
    image: redis:5.0
    ports:
      - 9001:6379
    networks:
      - app
networks:
  app:
    driver: bridge